# Generated by Django 4.2.11 on 2024-05-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_comment_parent_comment'),
        ('articles', '0006_alter_article_article_link'),
    ]

    operations = [
    ]
