# Generated by Django 4.2.11 on 2024-05-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('news', 'News'), ('ask', 'Ask'), ('show', 'Show')], default='news', max_length=10),
        ),
    ]
