# Generated by Django 4.2.12 on 2024-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
